export type { ScopeKey, ScopeKind } from "./identity/scope.ts";
export { groupScope, userScope, scopeKeyStr } from "./identity/scope.ts";
export type { IncomingMessage, OutgoingMessage } from "./session/message.ts";
export { ChatBotSession } from "./agent/bot-session.ts";
export type { BotSessionOptions } from "./agent/bot-session.ts";
export { buildSystemPrompt } from "./agent/system-prompt.ts";
export { createDefaultTools, wrapHarnessTool, wrapHarnessTools } from "./tools/index.ts";
export { createSendImageTool } from "./tools/send-image.ts";
export type { CreateSendImageToolOptions, ImageSender, SendImageInput } from "./tools/send-image.ts";
export { SessionManager } from "./session/session-manager.ts";
export type { SessionManagerOptions, ActiveScopeInfo, ActiveScopeDetail } from "./session/session-manager.ts";
export { HistoryStore } from "./session/history.ts";
export { MemoryStore } from "./session/memory.ts";
export { MemoryFiles } from "./session/memory-files.ts";
export { createLogger, addSink, setLogLevel, createConsoleSink } from "./logging.ts";
export type { Logger, LogEntry, LogSink, LogLevel } from "./logging.ts";
